services:

  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d/grafana_nginx.conf:/etc/nginx/conf.d/grafana_nginx.conf
    command:
      - '--log-opt tag="{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"'
    networks:
      - grafana-loki

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    restart: always
    ports:
      - 3100:3100
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/loki.yaml
    networks:
      - grafana-loki

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./config/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "-config.file=/etc/promtail/promtail-config.yml"
    depends_on:
      - loki
    networks:
      - grafana-loki

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall lokiLogsDataplane
    networks:
      - grafana-loki

networks:
  grafana-loki:
    name: grafana-loki
