
services:

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    restart: always
    ports: 
      - 3100:3100
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/loki.yaml

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    
  fake_log_generator:
    image: us-docker.pkg.dev/grafanalabs-global/docker-explore-logs-prod/fake-log-generator:latest
    container_name: fake_log_generator
    command: -url http://loki:3100/loki/api/v1/push
  
 





