
services:

  nginx:
    image: nginx:stable-alpine3.20-perl
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./config/nginx_logs:/var/log/nginx
    networks:
      - grafana-loki

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    restart: always
    ports: 
      - 3100:3100
    volumes:
      - ./config/loki/loki.yaml:/etc/loki/loki.yaml
    networks:
      - grafana-loki

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./config/alloy/config-alloy.yaml:/etc/alloy/config.alloy:ro
      - ./config/nginx_logs:/var/log/nginx:ro
    ports:
      - 12345:12345
    command:
      - run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data \/etc/alloy/config.alloy
    depends_on:
      - loki
    networks:
      - grafana-loki

  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=accessControlOnCall lokiLogsDataplane
    networks:
      - grafana-loki

networks:
  grafana-loki:
    name: grafana-loki
   
  
 





