---
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "debug"

positions: # enregistrement de la position de lecture des logs de Promtail
  filename: /tmp/positions.yaml
  sync_period: 10s
  
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: tail
    static_configs:
      - targets:
          - localhost
        labels:
          job: intellio
          app: intellio
          __path__: /var/log/nginx/*.log
    pipeline_stages:
      - match:
          selector: '{app="intellio"}'
          stages:
          - regex:
              expression: '(?P<remote>[^\s]\d{1,3}\.\d{1,3})\.(?P<host>\d{1,3}\.\d{1,3}) (?P<user>[^\s]*) (?P<user_auth>[^\s]*) \[(?P<time>[^\]]*)\] "(?P<method>\S+) (?P<path>[^\s]+) (?P<protocol>[^\"]+)" (?P<code>[^\s]*) (?P<size>[^ ]*) "(?P<referer>[^\"]*)" "(?P<agent>[^\"]*)" (?P<extras>[^\s]*)'         
          - labels: # donne un nom à chaque élément de la REGEX
              remote:
              host:
              user:
              user_auth:
              time:
              method:
              path:
              protocol:
              code: 
              size:
              referer:
              agent:
              extras:
          - labeldrop: # retire un label de la liste avant d'envoyer les logs à Loki
              - host
          - replace: # remplace le host de l'adresse IP par 0.0
              expression: '(?:\d{1,3}\.){2}(?P<host>\d{1,3}\.\d{1,3})'
              replace: "0.0"
          # - replace:
          #     expression: '(?:[^\s]\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}) [^\s]* [^\s]* \[[^\]]*\] "(?:\S+) (?P<path>[^\s]+) '
          #     source: path
          #     replace: "id"
          # - template: 
          #     source: path
          #     template: '{{ regexReplaceAll "[0-9]+" (toString .path) "id" }}'
    
