---
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml
  sync_period: 10s
  
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: tail
    static_configs:
      - targets:
          - localhost
        labels:
          job: intellio
          app: intellio
          __path__: /var/log/nginx/*.log
    pipeline_stages:
      - match:
          selector: '{app="intellio"}'
          stages:
          - regex:
              expression: "(?P<timestamp>\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2})"
          - replace:
              expression: ".*"
              replacement: "{.timestamp}"
          # - timestamp:
          #     source: timestamp
          #     format: "2006-01-02T15:04:05"
          # - output:
          #     source: timestamp
          #     format: '{{.timestamp}}'

    
