server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions: # enregistrement de la position de lecture des logs de Promtail
  filename: /tmp/positions.yaml
  sync_period: 10s

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: container_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: container_logs
          __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:
    - json:
        expressions:
          stream: stream
          attrs: attrs
          tag: attrs.tag

    - regex:
        expression: "(?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))"
        source: "tag"

          # - regex:
          # expression: "^\\/var\\/lib\\/docker\\/containers\\/(?P<container_id>.{12}).+\\/.+-json\\.log$"
          # source: filename

    - labels:
        tag:
        stream:
        image_name:
        container_name:
        image_id:
        container_id: