---
server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "debug"

positions:
  filename: /tmp/positions.yaml
  sync_period: 10s
  
clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: tail
    static_configs:
      - targets:
          - localhost
        labels:
          job: intellio
          app: intellio
          __path__: /var/log/nginx/*.log
    pipeline_stages:
      - match:
          selector: '{app="intellio"}'
          stages:
          - regex:
              expression: '(?P<remote>[^\s]\d{1,3}\.\d{1,3})\.(?P<host>\d{1,3}\.\d{1,3}) (?P<user>[^\s]*) (?P<user_auth>[^\s]*) \[(?P<time>[^\]]*)\] "(?P<method>\S+)(?: +(?P<path>[^\"]*?)?(?:\?+\S*)?(?: +\S*)?)" (?P<code>[^\s]*) (?P<size>[^ ]*) "(?P<referer>[^\"]*)" "(?P<agent>[^\"]*)" (?P<request_time_float>[^\s]*)'
          - labels: # donne un nom à chaque élément de la REGEX
              remote:
              host:
              user:
              user_auth:
              time:
              method:
              path: 
              code: 
              size:
              referer:
              agent:
              request_time_float:
          - labeldrop: # retire un label de la liste avant de l'envoyer à Loki
              - host
          - replace: # remplace un élément du log
              expression: ((?P<remote>[^\s]\d{1,3}\.\d{1,3})\.(?P<host>[^\s]\d{1,3}\.\d{1,3}))
              replace: "0.0"






        




    
