server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: nginx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx              
          app: nginx-server                
          instance: nginx-instance 
          __path__: /var/log/nginx/*.log
  # - job_name: journal
  #   journal: 
  #     max_age: 1h 
  #     path: /var/log/journal
  #     labels:
  #       job: systemd
  #       env: production
  #   relabel_configs: 
  #     - source_labels: ['__journal__systemd_unit']
  #       target_label: 'unit'