apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: false
    isDefault: true

  - name: Test
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "1"

# test création Datasources supplémentaire sur conteneur Grafana (Multi-Tenancy)
  - name: Grafana
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "grafana"